import json
from datetime import datetime

def escape_latex(text):
    """Escapes special LaTeX characters."""
    if not isinstance(text, str):
        return str(text)
    
    # Handle backslash first to avoid double escaping
    text = text.replace('\\', r'\textbackslash{}')
    
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text

def generate_latex_from_dict(data):
    latex_content = []
    
    # Header
    # Remove 'handout' to enable animations (multiple pages per slide)
    latex_content.append(r'\documentclass[17pt]{beamer}') 
    latex_content.append(r'\usetheme{Madrid}')    # Explicit date    # Enable bullet point animation
    # latex_content.append(r'\beamerdefaultoverlayspecification{<+->}')
    
    latex_content.append(r'\title{' + escape_latex(data.get('presentation_title', 'Presentation')) + '}')
    
    # Find title slide to extract subtitle/author info
    subtitle_text = ""
    author_text = "Generated by Agent"
    
    for slide in data.get('slides', []):
        if slide.get('type') == 'title_slide':
            content = slide.get('content', [])
            valid_content = [c for c in content if isinstance(c, str) and c.strip()]
            if valid_content:
                subtitle_text = " \\\\ ".join([escape_latex(c) for c in valid_content])
            break
            
    if subtitle_text:
        latex_content.append(r'\subtitle{' + subtitle_text + '}')
        
    latex_content.append(r'\author{' + author_text + '}')
    
    # Explicit date format (Day Month Year)
    current_date = datetime.now().strftime("%d %B %Y")
    latex_content.append(r'\date{' + current_date + '}')
    
    latex_content.append(r'\usefonttheme{structurebold}')
    
    # Remove slide numbers
    latex_content.append(r'\setbeamertemplate{footline}{}') 
    latex_content.append(r'\setbeamertemplate{navigation symbols}{}')
    
    latex_content.append(r'\begin{document}')
    latex_content.append(r'')

    # Title Slide with Logo
    latex_content.append(r'{%')
    latex_content.append(r'\usebackgroundtemplate{%')
    latex_content.append(r'  \vbox to \paperheight{\vfill\hbox to \paperwidth{\hfill\includegraphics[width=2cm]{logo.png}\hspace{0.5cm}}\vspace{0.5cm}}')
    latex_content.append(r'}%')
    latex_content.append(r'\frame{\titlepage}')
    latex_content.append(r'}')
    latex_content.append(r'')

    # Slides
    for slide in data.get('slides', []):
        if slide.get('type') == 'title_slide':
            # Handle Title Slide Content (Subtitle/Presenter)
            content = slide.get('content', [])
            valid_content = [c for c in content if isinstance(c, str) and c.strip()]
            if valid_content:
                # Add content as subtitle or extra text on title page
                # Since \titlepage is already generated, we can't easily inject into it 
                # unless we move \titlepage generation inside this loop or use \subtitle before it.
                # BUT \titlepage was generated above.
                # Let's add a second frame for "Introduction" if content exists?
                # OR better: Move \titlepage generation HERE.
                pass
            continue 
            
        latex_content.append(r'\begin{frame}')
        latex_content.append(r'\transfade') # Add fade transition
        latex_content.append(r'\frametitle{' + escape_latex(slide.get('title', '')) + '}')
        
        latex_content.append(r'\begin{columns}')
        
        # Left Column: Content
        latex_content.append(r'\begin{column}{0.5\textwidth}')
        
        # Use smaller font to prevent overflow
        latex_content.append(r'\small')
        
        itemize_items = []
        content = slide.get('content', [])
        # Filter valid strings
        valid_content = [c for c in content if isinstance(c, str) and c.strip()]
        
        # We use explicit overlay specifications <n-> to ensure exact page counts.
        # Page 1: Title Only (Intro narration). No items shown.
        # Page 2: Item 1 appears.
        # Page 3: Item 2 appears.
        # ...
        
        for idx, content_item in enumerate(valid_content):
            # idx=0 -> Page 2 (since Page 1 is Title Only)
            overlay_num = idx + 2
            itemize_items.append(r'\item<' + str(overlay_num) + r'-> ' + escape_latex(content_item))
                
        # Only create itemize environment if we have items
        if itemize_items:
            latex_content.append(r'\begin{itemize}')
            latex_content.extend(itemize_items)
            latex_content.append(r'\end{itemize}')
            
        latex_content.append(r'\end{column}')
        
        # Right Column: Image (if exists)
        latex_content.append(r'\begin{column}{0.5\textwidth}')
        if slide.get('image_path'):
            latex_content.append(r'\begin{figure}')
            latex_content.append(r'\centering')
            # Use forward slashes for paths even on Windows/Mac for LaTeX
            img_path = slide.get('image_path').replace('\\', '/')
            latex_content.append(r'\includegraphics[width=\textwidth]{' + img_path + '}')
            latex_content.append(r'\end{figure}')
            latex_content.append(r'\end{column}')
            latex_content.append(r'\end{columns}')
        
        latex_content.append(r'\end{frame}')
        latex_content.append(r'')

    # Footer
    latex_content.append(r'\end{document}')
    
    return '\n'.join(latex_content)

def json_to_latex(json_file, output_file):
    with open(json_file, 'r') as f:
        data = json.load(f)

    latex_content = generate_latex_from_dict(data)

    with open(output_file, 'w') as f:
        f.write(latex_content)
    
    print(f"Successfully generated {output_file}")

if __name__ == "__main__":
    json_to_latex('sample_slides.json', 'output.tex')
