apiVersion: 1

datasources:
  - name: Prometheus
    uid: slide-generator-prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false

  - name: Postgres
    uid: slide-generator-postgres
    type: postgres
    url: postgres:5432
    database: spoken_tutorial
    user: grafana_ro
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: false
    editable: false
