"""
Boilerplate slides generation node.
Generates the 7 fixed-format slides using LLM.

Slides generated:
1. Title Slide
2. Learning Objectives
3. System Requirements
4. Prerequisites
5. Summary
6. Assignment
7. Acknowledgement (Thank You)

Input: ScriptMetadata from metadata_node
Output: List of 7 boilerplate slides with narration + image_prompt
"""
import os
from dotenv import load_dotenv
from typing import List, Optional
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI 
from langchain_core.messages import SystemMessage, HumanMessage
from src.core.state import AgentState
import json

load_dotenv()


# === OUTPUT SCHEMA ===

class BoilerplateSlide(BaseModel):
    """A single boilerplate slide."""
    title: str = Field(description="Slide title")
    narration: str = Field(description="Full narration text, sentences separated by \\n")
    image_prompt: str = Field(description="Visual cue for the slide")


class BoilerplateSlides(BaseModel):
    """All 7 boilerplate slides."""
    title_slide: BoilerplateSlide
    learning_objectives_slide: BoilerplateSlide
    system_requirements_slide: BoilerplateSlide
    prerequisites_slide: BoilerplateSlide
    summary_slide: BoilerplateSlide
    assignment_slide: BoilerplateSlide
    acknowledgement_slide: BoilerplateSlide


# === MAIN NODE FUNCTION ===

def generate_boilerplate(state: AgentState) -> dict:
    """
    Generates the 7 boilerplate slides using LLM.
    
    These slides have a fixed structure but the narration
    is generated by LLM based on the metadata.
    """
    print("📄 Generating boilerplate slides...")
    
    metadata = state.get('metadata')
    
    if not metadata:
        print("⚠️ No metadata provided for boilerplate generation")
        return {"boilerplate_slides": None}
    
    # Initialize LLM with structured output
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash")
    llm_openai = ChatOpenAI(model="gpt-5.2")
    structured_llm = llm.with_structured_output(BoilerplateSlides)
    structured_llm_openai = llm_openai.with_structured_output(BoilerplateSlides)
    
    messages = get_boilerplate_messages(metadata)
    
    try:
        result = structured_llm_openai.invoke(messages)
        
        if result is None:
            print("⚠️ LLM returned None for boilerplate slides")
            return {"boilerplate_slides": None}
        
        # Convert to list format for easier merging later
        boilerplate_list = [
            result.title_slide.model_dump(),
            result.learning_objectives_slide.model_dump(),
            result.system_requirements_slide.model_dump(),
            result.prerequisites_slide.model_dump(),
            result.summary_slide.model_dump(),
            result.assignment_slide.model_dump(),
            result.acknowledgement_slide.model_dump(),
        ]
        
        print(f"✓ Generated {len(boilerplate_list)} boilerplate slides")
        
        return {"boilerplate_slides": boilerplate_list}
        
    except Exception as e:
        print(f"Boilerplate generation failed: {e}")
        return {"boilerplate_slides": None}


# === PROMPT MESSAGES ===

def get_boilerplate_messages(metadata: dict) -> list:
    """Messages for boilerplate slide generation."""
    
    system_content = """You are an instructional expert for creating Spoken Tutorials.

=== NARRATION RULES (CRITICAL) ===
1. Each sentence on a NEW LINE (use \\n between sentences)
2. Sentences MUST be ≤ 80 characters
3. Use **bold** for technical terms
4. Simple, conversational Indian English
5. Narration is what is SPOKEN ALOUD (no visual descriptions)

=== SLIDE SPECIFICATIONS ===

**1. TITLE SLIDE**
- title: Use the presentation_title exactly
- narration: ONE sentence only: "Welcome to the Spoken Tutorial on [topic]."
- image_prompt: "Title Slide"

**2. LEARNING OBJECTIVES SLIDE**
- title: Learning Objectives
- narration: By the end of this tutorial, you will be able to:\\n• [objective 1].\\n• [objective 2]...
- image_prompt: "Learning Objectives Slide"

**3. SYSTEM REQUIREMENTS SLIDE**
- title: System Requirements
- narration: 
- image_prompt: "System Requirements Slide"
- Infer appropriate requirements from the topic (e.g., browser for web topics, Python for coding)

**4. PREREQUISITES SLIDE**
- title: Prerequisites
- narration: [Prerequisites from metadata].\\n"For pre-requisite tutorials, please visit this website."
- image_prompt: "Pre-requisite Slide"

**5. SUMMARY SLIDE**
- title: Summary
- narration: "Let us summarize what we have learnt.\\n[Brief 2-3 sentence recap based on outline topics]."
- image_prompt: "Summary Slide"

**6. ASSIGNMENT SLIDE**
- title: Assignment
- narration: "As an assignment, [create a meaningful task based on learning objectives].\\n[One practical exercise for the learner]."
- image_prompt: "Assignment Slide"

**7. ACKNOWLEDGEMENT SLIDE**
- title: "Thank You"
- narration: "This Spoken Tutorial is brought to you by\\n**EduPyramids Educational Services Private Limited**, **SINE**, **IIT Bombay**.\\nThank you for joining."
- image_prompt: "EduPyramids logo"

Generate all 7 boilerplate slides based on the metadata provided."""

    human_content = f"""Generate slides for this tutorial:

METADATA:
{json.dumps(metadata, indent=2)}"""

    return [
        SystemMessage(content=system_content),
        HumanMessage(content=human_content)
    ]
