server {
    listen 80;
    
    server_name spokenai.live www.spokenai.live;

    location /{
        return 301 https://$host$request_uri;
    }
}
    
server {
    listen 443 ssl;
    server_name spokenai.live www.spokenai.live;
    ssl_certificate /etc/letsencrypt/live/spokenai.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/spokenai.live/privkey.pem;
    
    client_max_body_size 100M;

    location /{
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/{
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }

    location /static/ {
        proxy_pass http://backend:8000/static/;
    }

    location /output/ {
        proxy_pass http://backend:8000/output/;
    }
}